version: '3.7'
services:
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./pgdata1:/var/lib/postgresql/data
      - ./postgresql1.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"  # Expose port 5432 on the host to port 5432 in the container
    networks:
      - postgres

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./pgdata2:/var/lib/postgresql/data
      - ./postgresql2.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5433:5432"  # Expose port 5433 on the host to port 5432 in the container
    networks:
      - postgres

volumes:
  pgdata1:
  pgdata2:

networks:
  postgres:
    driver: bridge
